version: 2
models:
  - name: stg_orders
    description: Staging orders (cleaned)
    columns:
      - name: order_id
        description: Primary key
        tests: [unique, not_null]
      - name: customer_id
      - name: order_date
      - name: country
        tests:
          - accepted_values:
              values: ['US', 'UK', 'CA']
              quote: true
      - name: status